config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root "books#index"
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :books_category, dependent: :delete_all
    has_many :categories, through: :books_category
    validates :name, presence: true, uniqueness: true
    validates :author, presence: true
    validates :desc, presence: true, length: { minimum: 10 }
    validates :isbn, presence: true, length: { is: 13 }, uniqueness: true
end

app/models/books_category.rb
class BooksCategory < ApplicationRecord
  belongs_to :category
  belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books_category, dependent: :restrict_with_error
    has_many :books, through: :books_category
    validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
        flash[:alert] = "Você não está autorizado a executar esta ação."
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    current_page = (params[:page] || 1).to_i
    # Pesquisa
    @q = Book.ransack(params[:q])
    @books = @q.result.page(current_page).per(4)
    authorize @books

    
    
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    authorize @book
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "O livro foi criado com sucesso." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "O livro foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    if @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: "O livro foi excluído com sucesso." }
        format.json { head :no_content }
      end
    else
      redirect_to books_url, alert: @book.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      authorize @book
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :desc, :isbn, :date, :category_ids => [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    current_page = (params[:page] || 1).to_i
    @categories = Category.page(current_page).per(3)
  end

  # GET /categories/1 or /categories/1.json
  def show
    redirect_to  categories_path
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "A categoria foi criado com sucesso." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to  categories_path, notice: "A categoria foi atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: "A categoria foi excluída com sucesso." }
        format.json { head :no_content }
      end
    else
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/books/_book.html.erb
<div class="main-container">
  <div id="<%= dom_id book %>" class="book"=>
      <h1><%= book.name %></h1>

      <strong>Autor(a):</strong>
      <%= book.author %>

      <p>
        <%= book.desc %>
      </p>

    <p>
      <strong>ISBN:</strong>
      <%= book.isbn %>
    </p>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for book do |form| %>
  <%= form.error_notification %>
  <%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>

    <div class="container form_livro">
      <%= form.input :name, placeholder: 'Título' %>
      <%= form.input :author, placeholder: 'Autor' %>
      <%= form.input :desc, placeholder: 'Descrição' %>
      <%= form.input :date, label: 'Data de lançamento', html5: true%>
      <%= form.input :isbn, placeholder: 'ISBN' %>
      <%= form.association :categories, prompt: "Selecionar categoria", html5: true%>

      <%= form.button :submit, class: 'entrar' %>
    </div>
    
<% end %>

app/views/books/_pagination.html.erb
<nav>
    <%= link_to_previous_page @books, "Voltar |" %>
    <%= link_to_next_page @books, "Próximo" %>
</nav>

app/views/books/edit.html.erb
<div class="container">
<h1>Editando Livro</h1>

  <%= render "form", book: @book %>

  <div>
    <%= link_to "Mostrar livro", @book %> |
    <%= link_to "Voltar para livros", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<body>
  <main>
    <h1>Pergaminho</h1>
    <div class="pesquisa">

      <%= search_form_for @q do |f| %>
        <%= f.search_field :name_or_author_or_isbn_cont, placeholder:"Buscar por título, autor, obra...", 
                                       class:"barra-de-pesquisa"
                                       %>
        <%= f.button :Pesquisar, class:"pesquisa-btn" %> 
      <% end %>
    </div>
    <%= pluralize(@books.size, "Livro", "Livros")%>
    <div>
    <div class="livros">
          <% @books.each do |book| %>
            <ul class="card-livro">
                <li>
                  <%= link_to book.name, book, class: 'titulo' %> 
                  <%= book.author %> 
                </li>
                <li class="descricao_livro"><%= book.desc %></li>
            </ul>
          <% end %>
    </div>
    </div>
    <%= link_to "Novo livro", new_book_path%>
    <%= render 'pagination'%>
  </main>
  
</body> 

app/views/books/new.html.erb
<div class="main-container">
  <h1>Registrar novo livro</h1>

  <%= render "form", book: @book %>

  <div>
    <%= link_to "Página inicial", books_path %>
  </div>
</div>

app/views/books/show.html.erb
<%= render @book %>

<div class="ctg_links" >
  <%= link_to "Editar livro  ", edit_book_path(@book) %>  | 
  <%= link_to "  Voltar  ", books_path %> |
  <%= link_to "  Excluir livro", @book, method: :delete, data:{confirm: "Você quer deletar?"} %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="amostra_catg">
  <p class="nome_ctg">
    <%= category.name %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for category do |form| %>
  <%= form.error_notification %>
  <%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>

  <div class="container form_livro">
    <%= form.input :name, placeholder: 'Nome', autofocus: true %>
    <%= form.button :submit, class: 'entrar' %>
  </div>
<% end %>

app/views/categories/_pagination.html.erb
<nav>
    <%= link_to_previous_page @categories, "Voltar | " %>
    <%= link_to_next_page @categories, "Próximo" %>
</nav>

app/views/categories/edit.html.erb
<div class="main-container">
  <h1>Editando Categoria</h1>

  <%= render "form", category: @category %>

  <div>
    <%= link_to "Mostrar categoria", @category %> |
    <%= link_to "Voltar", categories_path %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="main-container">
  <h1>Categorias</h1>

  <div id="categories">
    <% @categories.each do |category| %>
      <div class="container amostra_catg">
        <%= render category %>
        <div>
        <p>
          <%= link_to 'Editar', edit_category_path(category), class:"ctg_links"%>
          <%= link_to 'Excluir categoria', category, method: :delete, data: { confirm: 'Você quer deletar?' }, class:"ctg_links"%>
        </p>
        </div>
      </div>
      
    <% end %>
  </div>

  <%= link_to "Nova categoria", new_category_path %>
  <%= render 'pagination' %>
</div>

app/views/categories/new.html.erb
<div class="main-container">
  <h1>Criar nova categoria</h1>

  <%= render "form", category: @category %>

  <div>
    <%= link_to "Voltar para categorias", categories_path %>
  </div>
</div>

app/views/layouts/_bar.html.erb
<% if user_signed_in? %>
<header class="menu">
    <p class="brand">Pergaminho<i class="fa-solid fa-book"></i></p>
    <div class="nav">
      <%= link_to "Início", root_path, class: 'inicio'%>
      <%= link_to "Categorias", categories_path, class: 'categorias' %>
      <%= link_to "Editar Perfil", edit_user_registration_path, class: 'perfil' %>
      <%= link_to "Sair", destroy_user_session_path, method: :delete, class:'sair'%>
      <button class='menu-btn'></button>
    </div>
  </header>
<% end %>

app/views/layouts/_flash_messages.html.erb
<p class="notices" ><% if notice.present? %>
    <%= notice%>
<% end %> </p>

<p class="notices red" ><% if alert.present? %>
    <%= alert%>
<% end %> </p>

app/views/layouts/_pagination.html.erb
<nav>
    <%= link_to_previous_page @books, "Back" %>
    <%= link_to_next_page @books, "Next" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pergaminho</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      src="https://kit.fontawesome.com/9674bc7d22.js"
      crossorigin="anonymous"
    </script>
  </head>

  <body>
    <%= render 'layouts/bar'%>
    <%= render 'layouts/flash_messages'%>
    <%= yield %>
    
    <footer>© 2022. Pergaminho. Todos os direitos reservados.</footer>

    <%= javascript_pack_tag 'app' %>  
  </body>
  
</html>